server:
    port: 8080

spring:
    cloud:
        gateway:
            routes:
            -   id: userModule
                uri: http://localhost:8081/
                predicates:
                - Path=/oauth/**,/accounts/**
            -   id: reserveModule
                uri: http://localhost:8082/
                predicates:
                - Path=/**
